lib/tasks1_web/router.ex
defmodule Tasks1Web.Router do
  use Tasks1Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasks1.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Tasks1Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    
    resources "/users", UserController
    resources "/tasks", TaskController
    resources "/timeblocks", TimeblockController

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", Tasks1Web do
    pipe_through :api
    resources "/manages", ManageController, except: [:new, :edit]
  end
end

lib/tasks1_web/templates/page/index.html.eex
<%= if !@current_user do %>
  <h1>Log In</h1>
  <!-- session_path(@conn, :create) -->
  <%= form_tag("/session", method: :post) do %>
    <div class="form-group">
      Username
      <input type="text" name="Username" placeholder="Enter your username" >
      <br>
      User ID
      <input type="number" name="user_id" placeholder="Enter your user id" >
      <%= link "Forgot your user id?", to: "/users" %>
    </div>
    <!-- passwords come later -->
    <div class="form-group">
      <button class="btn btn-primary">Log in</button>
      <%= link "Register", to: user_path(@conn, :new) %>
    </div>
  <% end %>
<% else %>
  <h1>Welcome to the task tracker!</h1>
<% end %>

lib/tasks1_web/templates/page/taskfeed.html.eex
<h1>Your Tasks</h1>
<br>
<h3> Incomplete tasks </h3>
<%= Enum.map @tasks, fn task -> %>
    <%= if (task.user == @current_user) && @current_user && !task.completed do %>
        <br>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <p><strong>Task: </strong><%= task.title %></p>
                        <p><strong>Description: </strong><%= task.description %></p>
                        <p><strong>Time Spent: </strong><%= task.time %> minutes</p>
                        <%= link "Update Task Progress", to: task_path(@conn, :edit, task) %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>
<br>
<h3> Completed tasks </h3>
<%= Enum.map @tasks, fn task -> %>
    <%= if (task.user == @current_user) && @current_user && task.completed do %>
        <br>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <p><strong>Task: </strong><%= task.title %></p>
                        <p><strong>Description: </strong><%= task.description %></p>
                        <p><strong>Time Spent: </strong><%= task.time %> minutes</p>
                        <%= link "Update Task Progress", to: task_path(@conn, :edit, task) %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>
<%= if !@current_user do %>
    No tasks to show. Make sure you're logged in!
<% end %>