lib/tasks1_web/router.ex
defmodule Tasks1Web.Router do
  use Tasks1Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasks1.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Tasks1Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    
    resources "/users", UserController
    resources "/tasks", TaskController
    resources "/timeblocks", TimeblockController

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", Tasks1Web do
    pipe_through :api
    resources "/manages", ManageController, except: [:new, :edit]
  end
end

lib/tasks1/work/task.ex
defmodule Tasks1.Work.Task do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasks1.Work.Task


  schema "tasks" do
    field :completed, :boolean, default: false
    field :description, :string
    field :time, :integer, default: 0
    field :title, :string
    belongs_to :user, Tasks1.Accounts.User

    timestamps()
  end

  @doc false
  def changeset(%Task{} = task, attrs) do
    task
    |> cast(attrs, [:title, :description, :time, :completed, :user_id])
    |> foreign_key_constraint(:user_id)
    |> validate_required([:title, :description, :time, :completed])
    |> validate_number(:user_id, greater_than: 0)
    |> validate_number(:time, greater_than_or_equal_to: 0)
  end
end

lib/tasks1_web/controllers/task_controller.ex
defmodule Tasks1Web.TaskController do
  use Tasks1Web, :controller

  alias Tasks1.Work
  alias Tasks1.Work.Task

  def index(conn, _params) do
    tasks = Work.list_tasks()
    current_user = conn.assigns[:current_user]
    users = Tasks1.Accounts.list_users()
    manages = if current_user do 
        Tasks1.Work.manages_map_for(current_user.id)
    else
      nil
    end
    render(conn, "index.html", tasks: tasks, manages: manages)
  end

  def new(conn, _params) do
    changeset = Work.change_task(%Task{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"task" => task_params}) do
    case Work.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Work.get_task!(id)
    timeblocks = Work.list_timeblocks()
    current_user = conn.assigns[:current_user]
    manages = if current_user do 
        Tasks1.Work.manages_map_for(current_user.id)
    else
      nil
    end
    render(conn, "show.html", task: task, timeblocks: timeblocks, manages: manages)
  end

  def edit(conn, %{"id" => id}) do
    task = Work.get_task!(id)
    timeblocks = Work.list_timeblocks()
    changeset = Work.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset, timeblocks: timeblocks)
  end

  def track(conn, %{"id" => id}) do
    task = Work.get_task!(id)
    changeset = Work.change_task(task)
    render(conn, "track.html", task: task, changeset: changeset)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Work.get_task!(id)

    case Work.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Work.get_task!(id)
    {:ok, _task} = Work.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: task_path(conn, :index))
  end
end

lib/tasks1_web/views/task_view.ex
defmodule Tasks1Web.TaskView do
  use Tasks1Web, :view
end

lib/tasks1_web/templates/task/edit.html.eex
<h2>Update Task Progress/Assignee</h2>
<h3>Task: <%= @task.title %></h3>
<h3>Description: <%= @task.description %></h3>
<h3>ID: <%= @task.id %></h3>
<h3>Time Spent: 
    <%= Enum.sum(Enum.map(@timeblocks, fn(x) -> if x.task_id == @task.id, do: abs(NaiveDateTime.diff(x.start, x.end, :second)), else: 0 end)) / 60 %> minutes  
</h3>

<%= if @current_user do %>
    <%= render "progress.html", Map.put(assigns, :action, task_path(@conn, :update, @task)) %>
<% else %>
    <h2><%= link "Log in", to: "/" %> to be able to update task progress!</h2>
<% end %>

<span><%= link "Cancel", to: task_path(@conn, :index) %></span>

lib/tasks1_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, "Assign to a User by user ID (optional)", class: "control-label" %>
    <%= text_input f, :user_id, class: "form-control" %>
    <%= error_tag f, :user_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasks1_web/templates/task/index.html.eex
<h1>Tasks</h1>
<h3>Incomplete Tasks</h3>
<table class="table">
  <thead>
    <tr>
      <th>Task</th>
      <th>Time Spent</th>
      <th>Assigned to</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
  <%= if !task.completed do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.time %> min.</td>
      <%= if task.user do %>
        <td>
          <%= task.user.name %>
        </td>
      <% else %>
        <td>
          <strong>No User Assigned</strong>
        </td>
      <% end %>

      <td class="text-right">
        <span><%= link "View", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        <%= if @current_user do %>
          <%= if !task.user || task.user == @current_user || @manages[task.user.id] do %>
            <span><%= link "Update Progress/Reassign", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
          <% end %>
          <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        <% end %>
      </td>
    </tr>
  <% end %>
<% end %>
  </tbody>
</table>

<h3>Completed Tasks</h3>
<table class="table">
  <thead>
    <tr>
      <th>Task</th>
      <th>Time Spent</th>
      <th>Assigned to</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
  <%= if task.completed do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.time %> min.</td>
      <%= if task.user do %>
        <td>
          <%= task.user.name %>
        </td>
      <% else %>
        <td>
          <strong>No User Assigned</strong>
        </td>
      <% end %>

      <td class="text-right">
        <span><%= link "View", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        <%= if @current_user do %>
          <%= if !task.user || @manages[task.user.id] do %>
            <span><%= link "Update Progress/Reassign", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
          <% end %>
          <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        <% end %>
      </td>
    </tr>
  <% end %>
<% end %>
  </tbody>
</table>

lib/tasks1_web/templates/task/new.html.eex
<h2>New Task</h2>


<%= if @current_user do %>
    <%= render "form.html", Map.put(assigns, :action, task_path(@conn, :create)) %>
<% else %>
    <h2><%= link "Log in", to: "/" %> to be able to create new tasks!</h2>
<% end %>


<span><%= link "Back to See All Tasks", to: task_path(@conn, :index) %></span>

lib/tasks1_web/templates/task/progress.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  <%= if @current_user == @task.user do %>

    <span><%= link "Add a time block", to: timeblock_path(@conn, :new) %></span>

    <div class="form-group">
      <%= label f, :completed, class: "control-label" %>
      <%= checkbox f, :completed, class: "checkbox" %>
      <%= error_tag f, :completed %>
    </div>

    
  <% else %>
    <h3>Time Spent: <%= @task.time %> minutes</h3>
    <h3>Completed: <%= @task.description %></h3>
  <% end %>

  <div class="form-group">
    <%= label f, "Assign to a user by id", class: "control-label" %>
    <%= text_input f, :user_id, class: "form-control" %>
    <%= error_tag f, :user_id %>
  </div>

  <div class="form-group">
    <%= submit "Confirm", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasks1_web/templates/task/show.html.eex
<h2>Task: <%= @task.title %></h2>

<ul>

  <li>
    <strong>Description:</strong>
    <%= @task.description %>
  </li>

  <%= if @task.user do %>
    <li>
      <strong>Assigned to:</strong>
      <%= @task.user.name %>
    </li>
  <% else %>
    <li>
      <strong>Not Assigned to a User</strong>
    </li>
  <% end %>

  <li>
    <strong>Task ID:</strong>
    <%= @task.id %>
  </li>


  <li>
    <strong>Completed:</strong>
    <%= @task.completed %>
  </li>

  <li>
    <strong>Time Blocks:</strong>
    <%= Enum.map @timeblocks, fn timeblock -> %>
      <%= if timeblock.task_id == @task.id do %>
        <br>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                      <p><strong>Start: </strong><%= timeblock.start %></p>
                      <p><strong>End: </strong><%= timeblock.end %></p>
                      <p><strong>Time Spent: </strong><%= abs(NaiveDateTime.diff(timeblock.start, timeblock.end, :second)) / 60 %> minutes</p>
                      <span><%= link "Edit", to: timeblock_path(@conn, :edit, timeblock), class: "btn btn-default btn-xs" %></span>
                    </div>
                </div>
            </div>
        </div>
      <% end %>
    <% end %>
  </li>

  <li>
    <strong>Total time spent:</strong>
    <%= Enum.sum(Enum.map(@timeblocks, fn(x) -> if x.task_id == @task.id, do: abs(NaiveDateTime.diff(x.start, x.end, :second)), else: 0 end)) / 60 %> minutes
  </li>

</ul>

<%= if @current_user do %>
  <%= if !@task.user || @task.user == @current_user || @manages[@task.user.id] do %>
    <span><%= link "Update Progress/Reassign", to: task_path(@conn, :edit, @task), class: "btn btn-default btn-xs" %></span>
  <% end %>
<% end %>
<br>
<span><%= link "Back to Tasks", to: task_path(@conn, :index) %></span>